use Sales

create table CATEGORY(
ID int primary key identity(1,1),
NAME nvarchar(30),
);

create table PRODUCT(
ID int  PRIMARY KEY identity(1,1) ,
NAME nvarchar(20),
BYPRICE MONEY,
SALEPRICE MONEY ,
QTY FLOAT,
CATEGORYID INT REFERENCES CATEGORY(ID)
);

CREATE TABLE CUSTOMER(
ID INT PRIMARY KEY IDENTITY(1,1),
NAME NVARCHAR(30),
PHONE NCHAR(11),
ADDRESS NVARCHAR(50),
BIRTHDATE DATETIME2
);
CREATE TABLE SALEORDER(
ID INT PRIMARY KEY IDENTITY(1,1),
DATEORDE DATETIME2,
CUSOMERID INT REFERENCES CUSTOMER(ID),
TOTALORDER MONEY
);
CREATE TABLE SALEORDERPRODUCT(
PRODUCTPRICE MONEY,
PRODUCTQUANTITY FLOAT,
PRODUCTTOTALPRICE MONEY,
ORDERID INT REFERENCES SALEORDER(ID),
PRODUCTID INT REFERENCES PRODUCT(ID),
PRIMARY KEY (ORDERID , PRODUCTID)

);

CREATE TABLE STOCK (
ID INT PRIMARY KEY IDENTITY(1,1),
NAME NVARCHAR(30),
TOTALMONEY MONEY
);

CREATE TABLE STOCKDETAILS
(
ID INT PRIMARY KEY IDENTITY(1,1),
STOCKID INT REFERENCES STOCK(ID),
TYPE INT,
TOTAL MONEY,
DATE DATETIME2,
ORDERID INT REFERENCES SALEORDER(ID),

);
